# cd happy
# instaloader "happsters" "happythoughtsdaily" "happy.little.thing" "happycolorfulgrowth" "happilyeverco" --no-videos --post-filter='date_utc >= datetime(20232023,3,1512023,3,151) and date_utc <= datetime(2018,1,1)'
# instaloader "happygirllife" "happyplaceofficial" "happynotesofficial" "happyplacemovement" "happyhourprojects" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "happiness.first" "happinessfirstco" "happiness_first_" "happiness_first_movement" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "happiness_first_project" "happinessfirststudio" "my.happiness.first" "happiness_first_now" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "happiness_first_always" "happiness_first_official" "love" "love.watts" "loveandwildhearts" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "loveonmute" "loversoftruth" "love__lovely" "loves_united_life" "love.without.restrictions" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "loveconquersall" "loveandbeloved" "smile" "smiletherapyofficial" "smileforacause" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "smile.because.you.can" "smilewithsade" "smileitsme" "smilemoreoften" "smilethatlightsupmyworld" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "smileloversclub" "smilinglife" "beautifuldestinations" "the.beautiful.mind" "beautifulinspiration_" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "beautifull_and_youknowit" "beautifulcuisines" "beautifulhealthylife" "beautifulplaces__" "beautifulhumanity" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "beautifulworld.life" "beautyofnature_world" "positivelypresent" "positive_vibes_movement" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "positiveaffirmationsdaily" "positiveenergyplus" "positivemindsetdaily" "positive.vibes.only_" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "positivitysparkles" "positivelifestyletribe" "positivechangeofficial" "positivityinspires" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "peacefulmindpeacefullife" "world_peace_project" "peacecollective" "peacerevolution21" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "peaceful_soul_" "inner.peace.project" "peaceful_barb" "peaceful_world_" "peace_love_humanity" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "bepositiveandpeaceful" "fun" "funny" "funny_memes_daily_" "funnyvideos" "funandloving" "funnyposts" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
# instaloader "funnyvideoss_" "funnyclipsonly" "funnyposts.daily" "funnyanimals_clu" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'

cd sad
instaloader "sadness_speaks" "weeping_heart_" "mourning_sunshine" "tearful_thoughts" "solitude_sighs" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "heartache_haven" "broken_spirit_" "sorrowful_soul_" "regretful_rain_" "emotional_eclipse" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "sad_talks" "the.saddest.girl" "sadquotespage" "sad.stufff" "sadworld.co" "sad.aestheticz" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "sad.edit.society" "depressed.soulsociety" "sadlifeig" "feelingsad_today" "tears.and.rain" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "cry__alone" "crybaby" "cryforhelp" "cry.sta" "crying.souls" "tears_of_my_heart" "crynomore" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "cryingintheclub" "cry.therapy" "sadlifeig" "sadlife.posts" "the.sad.life" "sadlife_ig" "sad_life_quotes" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "sadlifeforever" "sad.life.mood" "sad_life_vibes" "sad.life.lessons" "sad.life.project" "lonely" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "lonely_planet" "lonely_girl" "lonely.dreams" "lonely_landscape" "lonely_wall" "lonely_moments_" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "lonelybeauties" "lonely.road_" "lonely.crybaby" "badgalriri" "badboi" "badvibesforever" "badgal_nini" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "badideasclub" "badtothebone" "baddiewinkle" "badgirlzzclub" "bad_kids_club" "bad_teenagers" "broken_isnt_bad" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "broken_but_healing" "broken_hearted_therapy" "brokenmirrorart" "thebrokenplate" "brokenheartquotes" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "broken_trust_quotes" "broken.heartclub" "broken_hearted_girls" "brokenbutbeautifullymade" "healing_from_heartbreak" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "heartbreaksociety" "heartbreak.motel" "heartbreak_diaries" "healingheartbreak" "heartbreakchic" "heartbreaktravels" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'
instaloader "theheartbreaksocial" "heartbreaksurvivor" "heartbreak_problem" --no-videos --post-filter='date_utc >= datetime(2018,1,1) and date_utc <= datetime(2023,3,15)'